### ISSUE TITLE
Usage instructions

### ISSUE THREAD

**Issue by benjick** [xavczen/nextjs-page-transitions#6]
Would be great to have some instructions on how to use this, demo looks super cool!

**Comment by xavczen** [comment]
Hey! Thanks for your interest, there is actually not much to do with this app, except looking around the components and how it's built.

The instructions are here: https://github.com/xavczen/nextjs-page-transitions#build-setup

And the app is being refactored here: https://github.com/xavczen/nextjs-page-transitions/tree/refresh-that-hacky-implementation-with-some-cool-new-architecture (see commit by commit)

Have fun!
